export const CREATE_MOVIE_DATA = 'CREATE_MOVIE_DATA'
export const CREATE_MOVIE = 'CREATE_MOVIE'
export const DELETE_MOVIE_DATA = 'DELETE_MOVIE_DATA'
export const UPDATE_MOVIE_DATA = 'UPDATE_MOVIE_DATA'
export const GET_MOVIE_DATA = 'GET_MOVIE_DATA'
export const VIEW_MOVIE_DATA = 'VIEW_MOVIE_DATA'
export const EMPTY_MOVIE_ID = "EMPTY_MOVIE_ID"
export const SEARCH_MOVIE_DATA = "SEARCH_MOVIE_DATA"
export const SET_SELECTED_GENRE = "SET_SELECTED_GENRE"
export const CREATE_MOVIE_ERROR = "CREATE_MOVIE_ERROR"

// login
export const SIGNUP_USER = "SIGNUP_USER"
export const LOGIN_USER = "LOGIN_USER"
export const LOGIN_USER_FAIL = "LOGIN_USER_FAIL"
export const LOGOUT = "LOGOUT"

export const ERROR = "ERROR"
export const SUCCESS = "SUCCESS"